### ISSUE TITLE
Error during search Cannot read property 'air:NumberOfPieces' of undefined

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#115]
"errorMessage": "{\"errors\":\"TypeError\",\"message\":\"Cannot read property 'air:NumberOfPieces' of undefined\",\"stack\":\"TypeError: Cannot read property 'air:NumberOfPieces' of undefined\\n    at getBaggage (/var/task/node_modules/uapi-json/build/Services/Air/AirFormat.js:19:10)\\n    at formatTrip (/var/task/node_modules/uapi-json/build/Services/Air/AirFormat.js:50:18)\\n    at /var/task/node_modules/uapi-json/build/Services/Air/AirFormat.js:133:12\\n    at Array.map (native)\\n    at getTripsFromBooking (/var/task/node_modules/uapi-json/build/Services/Air/AirFormat.js:110:45)\\n    at /var/task/node_modules/uapi-json/build/Services/Air/AirFormat.js:177:21\\n    at /var/task/node_modules/uapi-json/node_modules/lodash/index.js:2275:27\\n    at /var/task/node_modules/uapi-json/node_modules/lodash/index.js:3073:15\\n    at baseForOwn (/var/task/node_modules/uapi-json/node_modules/lodash/index.js:2046:14)\\n    at /var/task/node_modules/uapi-json/node_modules/lodash/index.js:3043:18\\n    at baseMap (/var/task/node_modules/uapi-json/node_modules/lodash/index.js:2274:7)\"}"

**Comment by shmuga** [comment]
Fixed with #120
