### ISSUE TITLE
Error in importPNR parser.

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#156]
ImportPNR throwing error with next xml response 

Error:
```
TypeError: Cannot convert undefined or null to object
    at record.air:AirReservation.map.booking (/Users/mark/Workspace/JS/node-uapi-git/src/Services/Air/AirParser.js:446:26)
    at Array.map (native)
    at Parser.extractBookings (/Users/mark/Workspace/JS/node-uapi-git/src/Services/Air/AirParser.js:398:39)
    at Parser.importRequest (/Users/mark/Workspace/JS/node-uapi-git/src/Services/Air/AirParser.js:550:36)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

```
<?xml version="1.0" encoding="utf-8"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<universal:UniversalRecordImportRsp xmlns:universal="http://www.travelport.com/schema/universal_v36_0" xmlns:common_v36_0="http://www.travelport.com/schema/common_v36_0" xmlns:air="http://www.travelport.com/schema/air_v36_0" TraceId="" TransactionId="8F2887880A0742608C5624FBDD83C25A" ResponseTime="1028">
			<common_v36_0:ResponseMessage Code="0" Type="Warning" ProviderCode="1G">PNR already exists in Universal Record TBQCMK</common_v36_0:ResponseMessage>
			<universal:UniversalRecord LocatorCode="TBQCMK" Version="2" Status="Active">
				<common_v36_0:BookingTraveler Key="BcHDtpBAAA/BsHYZPIAAAA==" TravelerType="ADT" Age="48" DOB="1968-07-25" Gender="M">
					<common_v36_0:BookingTravelerName First="SKYWALKER" Last="ANAKIN"/>
					<common_v36_0:PhoneNumber Key="BcHDtpBAAA/BxHYZPIAAAA==" Type="Other" Location="IEV" CountryCode="380" Number="9379992">
						<common_v36_0:ProviderReservationInfoRef Key="BcHDtpBAAA/B92pZPIAAAA=="/>
					</common_v36_0:PhoneNumber>
					<common_v36_0:SSR Key="BcHDtpBAAA/ByHYZPIAAAA==" Status="HK" Type="DOCS" FreeText="P/UA/ES221731/UA/25JUL68/M/02MAR18/ANAKIN/SKYWALKER -1ANAKIN/SKYWALKER" Carrier="WS" ProviderReservationInfoRef="BcHDtpBAAA/B92pZPIAAAA=="/>
				</common_v36_0:BookingTraveler>
				<universal:ProviderReservationInfo Key="BcHDtpBAAA/B92pZPIAAAA==" ProviderCode="1G" LocatorCode="66GLWM" CreateDate="2017-03-02T11:38:14.542+00:00" ModifiedDate="2017-03-02T13:14:43.305+00:00" HostCreateDate="2017-03-02" OwningPCC="7J8J">
					<universal:ProviderReservationDetails ProviderReservationDetail="false" CustomCheck="true" ProviderProfile="false" DivideDetails="false" EnhancedItinModifiers="false" IntegratedContent="false" Cruise="false" RailSegment="false"/>
				</universal:ProviderReservationInfo>
				<air:AirReservation LocatorCode="0YCXP5" CreateDate="2017-03-02T11:38:13.633+00:00" ModifiedDate="2017-03-02T13:14:04.664+00:00">
					<common_v36_0:SupplierLocator SupplierCode="WS" SupplierLocatorCode="JDFQYT" ProviderReservationInfoRef="BcHDtpBAAA/B92pZPIAAAA==" CreateDateTime="2017-03-02T11:38:00.000+00:00"/>
					<common_v36_0:BookingTravelerRef Key="BcHDtpBAAA/BsHYZPIAAAA=="/>
					<common_v36_0:ProviderReservationInfoRef Key="BcHDtpBAAA/B92pZPIAAAA=="/>
				</air:AirReservation>
				<common_v36_0:AgencyInfo>
					<common_v36_0:AgentAction ActionType="Created" AgentCode="UAPI7980742859-07362D4F" BranchCode="257f/VZmSaKqfMsUWfwY6Q==" AgencyCode="TVPORTDYNASKLTONWABAGENCY" EventTime="2017-03-02T11:38:10.333+00:00"/>
					<common_v36_0:AgentAction ActionType="Modified" AgentCode="UAPI7980742859-07362D4F" BranchCode="P2731609" AgencyCode="S1473516" EventTime="2017-03-02T13:14:04.664+00:00"/>
				</common_v36_0:AgencyInfo>
			</universal:UniversalRecord>
		</universal:UniversalRecordImportRsp>
	</SOAP:Body>
</SOAP:Envelope>
```

**Comment by shmuga** [comment]
Closed in #157
