### ISSUE TITLE
Error: Cannot find module '../../src/error-types'

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#164]
After installing uapi-json from `npm` it's unusable last throws following error:

```
Error: Cannot find module '../../src/error-types'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/search-bookings-by-name/node_modules/uapi-json/build/utils/has-all-required-fields.js:7:19)
```

**Comment by dchertousov** [comment]
Closed in #166
