### ISSUE TITLE
Error parsing booking containing non-service passive segments

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#274]
If passive segment is no a service segment, then there is an issue parsing such a booking file

```
TypeError: Cannot convert undefined or null to object
    at Object.formatTrip (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirFormat.js:67:29)
    at indexedSegments.map.segment (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:580:19)
    at Array.map (native)
    at record.air:AirReservation.map.booking (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:579:25)
    at Array.map (native)
    at Parser.extractBookings (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:484:39)
    at Parser.importRequest (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:776:36)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by dchertousov** [comment]
Closed by #275
