### ISSUE TITLE
getPNR parsing issue

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#323]
```
TypeError: Cannot convert undefined or null to object
    at Object.formatTrip (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirFormat.js:65:29)
    at indexedSegments.map.segment (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:634:19)
    at Array.map (native)
    at record.air:AirReservation.map.booking (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:633:25)
    at Array.map (native)
    at Parser.extractBookings (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:549:39)
    at Parser.importRequest (/Users/dchertousov/Projects/uapi-json/src/Services/Air/AirParser.js:843:36)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by dchertousov** [comment]
Fixed by #324
