### ISSUE TITLE
AIR_CREATE_RESERVATION_REQUEST template has issues

### ISSUE THREAD

**Issue by jthoma** [Travelport-Ukraine/uapi-json#455]
While trying to do AirService.book, and params passed does (not) have "ssr" property, the error comes from handlebars helper equal doesn\'t match if - 56:23

**Comment by eugeniumegherea** [comment]
I encountered the same issue

`Error: equal doesn't match if - 56:23
    at validateClose (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/helpers.js:9:11)
    at Object.prepareBlock (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/helpers.js:132:5)
    at Object.anonymous (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/parser.js:52:21)
    at Parser.parse (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/parser.js:283:36)
    at parseWithoutProcessing (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/base.js:24:20)
    at HandlebarsEnvironment.parse (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/base.js:30:13)
    at compileInput (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/compiler.js:532:19)
    at ret (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/handlebars/lib/handlebars/compiler/compiler.js:546:18)
    at prepareRequest (/home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/uapi-json/src/Request/prepare-request.js:9:23)
    at /home/eugen/Projects/cyberwhale/cyberwhale-travelport/node_modules/uapi-json/src/Request/uapi-request.js:180:25 {
  description: undefined,
  fileName: undefined,
  lineNumber: 56,
  endLineNumber: 56,
  message: "equal doesn't match if - 56:23",
  name: 'Error',
  number: undefined,
  column: 23,
  endColumn: 28
}`

**Comment by jthoma** [comment]
I made a change in my local copy, to `src/Services/Air/templates/AIR_CREATE_RESERVATION_REQUEST.handlebars.js`. The current code is like in [22a21e8-55-61.txt](https://github.com/Travelport-Ukraine/uapi-json/files/4270786/22a21e8-55-61.txt) which I changed to [patch.txt](https://github.com/Travelport-Ukraine/uapi-json/files/4270787/patch.txt).

After the change, my bookings are going through.

**Comment by jthoma** [comment]
Actually got the issue.. it was just missing one '{'  from '{{#if carrier}}' on line 59

**Comment by creduo** [comment]
Sorry, looks like this one is my mistake. I made PR on this.
