### ISSUE TITLE
availability error

### ISSUE THREAD

**Issue by Shazad0304** [Travelport-Ukraine/uapi-json#613]
Service :

AirService.availability({
    legs: [{
        from: 'KHI',
        to: 'DXB',
        departureDate: '2023-01-10'
    }],
    passengers: {
        ADT: 1,
        INF: 0,
        CNN: 0,
    },
    cabins: ['Business', 'Economy'],
    allowDirectAccess: false,

});

Response: 

Response SOAP:  <SOAP:Envelope 
  xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Data</faultcode>
      <faultstring>Error unmarshalling message body: Expected "{http://www.travelport.com/schema/air_v52_0}PreferredCabins" end tag, found "{http://www.travelport.com/schema/common_v52_0}CabinClass" start tag (line 23, col 57, in UTF-8)</faultstring>
      <detail>
        <common_v52_0:ErrorInfo
          xmlns:common_v52_0="http://www.travelport.com/schema/common_v52_0">
          <common_v52_0:Code>1005</common_v52_0:Code>
          <common_v52_0:Service>WEBSVC</common_v52_0:Service>
          <common_v52_0:Type>Data</common_v52_0:Type>
          <common_v52_0:Description>Unable to parse XML stream</common_v52_0:Description>
          <common_v52_0:TransactionId>920C0E750A0D6A9270CC6884D25408DF</common_v52_0:TransactionId>
          <common_v52_0:TraceId/>
        </common_v52_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
err RequestRuntimeError.UAPIServiceError: UAPI Service responded with an error

**Comment by MohammaedAlani** [comment]
Same issue :(

Input params  {
  "legs": [
    {
      "from": "IEV",
      "to": "NYC",
      "departureDate": "2023-01-20"
    }
  ],
  "passengers": {
    "ADT": 1
  },
  "cabins": [
    "Economy"
  ],
  "requestId": "4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60",
  "maxJourneyTime": 300,
  "pricing": {
    "currency": "USD"
  }
}
Request URL:  https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService
Request XML:  
<soap:Envelope 
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:AvailabilitySearchReq
            AuthorizedBy="user" TraceId="4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60" TargetBranch="P7002726"
            
      xmlns:air="http://www.travelport.com/schema/air_v52_0"
            
      xmlns:com="http://www.travelport.com/schema/common_v52_0"
            >
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="IEV" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="NYC" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2023-01-20"/>
        <air:AirLegModifiers >
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers
                    MaxJourneyTime="300"
                IncludeFlightDetails="true"
            >
        <air:PreferredProviders>
          <com:Provider Code="1G" 
            xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
          </air:PreferredProviders>
        </air:AirSearchModifiers>
        <com:SearchPassenger Code="ADT" 
          xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
        </air:AvailabilitySearchReq>
      </soap:Body>
    </soap:Envelope>

Response SOAP:  <SOAP:Envelope 
  xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.System</faultcode>
      <faultstring>Error From Host: No availability on chosen flights.</faultstring>
      <detail>
        <common_v52_0:ErrorInfo 
          xmlns:common_v52_0="http://www.travelport.com/schema/common_v52_0">
          <common_v52_0:Code>3037</common_v52_0:Code>
          <common_v52_0:Service>AIRSEARCH_SERVICE</common_v52_0:Service>
          <common_v52_0:Type>System</common_v52_0:Type>
          <common_v52_0:Description>Error From Host: No availability on chosen flights.</common_v52_0:Description>
          <common_v52_0:TransactionId>9CF30F950A0D6A946E2AB71586D372F6</common_v52_0:TransactionId>
          <common_v52_0:TraceId>4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60</common_v52_0:TraceId>
        </common_v52_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
AirRuntimeError.NoResultsFound: No results found
    at Parser.AirErrorHandler (/Users/mohammedyounis/Workable/nodejs/mo/travelport_api_services/node_modules/uapi-json/src/Services/Air/AirParser.js:540:13)
    at validateSOAP (/Users/mohammedyounis/Workable/nodejs/mo/travelport_api_services/node_modules/uapi-json/src/Request/uapi-request.js:164:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  source: 'uapi-json',
  data: {
    faultcode: 'Server.System',
    faultstring: 'Error From Host: No availability on chosen flights.',
    detail: { 'common_v52_0:ErrorInfo': [Object] }
  },
  statusCode: 598
}

**Comment by MohammaedAlani** [comment]
any update on this issue?

**Comment by kommandant-topp** [comment]
Hello @MohammaedAlani, thank you for your request!

 I've checked the documentation, and it still states, `PreferredCabins requests availability for the selected cabin classes. Only one cabin can be requested. If that class is not available, an alternate cabin may be returned. Depending on availability and processing, either a cabin downgrade or upgrade may be offered `
So, we're still waiting for the multiple cabins to be allowed for the availability request.

Write me back if you have any other questions. Thank you, and have a nice day!

**Comment by Shazad0304** [comment]
payload : 

HotelService.search({
        code: 'DXB', 
        location : 'DXB',
        startDate: '2023-03-01',
        endDate: '2023-03-20',
        currency: 'USD',
        MaxWait: 30000,
        MaxProperties: 9999,
        rooms: [{
          adults: 1,
        }, {
          adults: 2,
        }],
        rating: [3, 5],
      }).then(
        resp => res.status(200).json(resp),
        err => console.log(err)
      )



Response SOAP:  <SOAP:Envelope
  xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Data</faultcode>
      <faultstring>Error unmarshalling message body: Expected "{http://www.travelport.com/schema/hotel_v47_0}HotelSearchAvailabilityReq" end tag, found "{http://www.travelport.com/schema/common_v52_0}BillingPointOfSaleInfo" start tag (line 6, col 61, in UTF-8)</faultstring>
      <detail>
        <common_v47_0:ErrorInfo
          xmlns:common_v47_0="http://www.travelport.com/schema/common_v47_0">
          <common_v47_0:Code>1005</common_v47_0:Code>
          <common_v47_0:Service>WEBSVC</common_v47_0:Service>
          <common_v47_0:Type>Data</common_v47_0:Type>
          <common_v47_0:Description>Unable to parse XML stream</common_v47_0:Description>
          <common_v47_0:TransactionId>D3CB77250A0D6A9311212696E753685D</common_v47_0:TransactionId>
        </common_v47_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
UnhandledError [RequestRuntimeError.UnhandledError]: Error during request. Please try again later
    at Parser.errorHandler (E:\projects\travelPortNodeTest\node_modules\uapi-json\src\Services\Hotels\HotelsParser.js:251:13)
RuntimeError.HotelsRuntimeError: Hotels service runtime error
    at Parser.errorHandler (E:\projects\travelPortNodeTest\node_modules\uapi-json\src\Services\Hotels\HotelsParser.js:251:58)
    at validateSOAP (E:\projects\travelPortNodeTest\node_modules\uapi-json\src\Request\uapi-request.js:164:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  source: 'uapi-json',
  data: null,
  statusCode: undefined,
  causedBy: HotelsRuntimeError [RuntimeError.HotelsRuntimeError]: Hotels service runtime error
      at Parser.errorHandler (E:\projects\travelPortNodeTest\node_modules\uapi-json\src\Services\Hotels\HotelsParser.js:251:58)
      at validateSOAP (E:\projects\travelPortNodeTest\node_modules\uapi-json\src\Request\uapi-request.js:164:29)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    source: 'uapi-json',
    data: {
      faultcode: 'Server.Data',
      faultstring: 'Error unmarshalling message body: Expected "{http://www.travelport.com/schema/hotel_v47_0}HotelSearchAvailabilityReq" end tag, found "{http://www.travelport.com/schema/common_v52_0}BillingPointOfSaleInfo" start tag (line 6, col 61, in UTF-8)',
      detail: [Object]
    },
    statusCode: undefined
  }
}
